---
title: "Using the PokeAPI"
author: "Maxwell Marion-Spencer"
date: '2022-06-18'
output: html_document
---

---- ACTUAL REPORT SECTION ----

## Requirements

List of requirements:

- `tidyverse`
- `httr`
- `jsonlite`

## Functions

---> 0. Pokemon - Pulls in weight, height, type and base stats (hp, attack,
defense, special attack, special defense, speed)

---> 1. Habitat - Asks for habitat as an argument, returns a data frame of
the habitat name as the column name, and all pokemon that can be found in that
habitat as the rows

---> 2. Color - Asks for color as an argument, returns a data frame of
the habitat name as the column name, and all pokemon that can be found in that
habitat as the rows

---> 3. Berry - Requests a berry name, returns growth_time, max_harvest, size,
smoothness, soil_dryness, firmness (?), and flavor (?)


## Exploratory Data Analysis

## Conclusion

---- ACTUAL REPORT SECTION ----

```{r}
#install.packages("jsonlite")
#install.packages("httr")

library(jsonlite)
library(httr)

# Format for queries
#  https://pokeapi.co/api/v2/

# Example query that pulls down a list of all pokemon
#  https://pokeapi.co/api/v2/pokemon?limit=100000&offset=0
```

```{r}
# Submitting test GET request
all_poke <- GET('https://pokeapi.co/api/v2/pokemon?limit=100000&offset=0')

all_poke_parsed <- fromJSON(rawToChar(all_poke$content))
str(all_poke_parsed, max.level = 1)
```

```{r}
all_poke_parsed <- as.data.frame(all_poke_parsed$results)
```

```{r}
# Testing pulling info for a single pokemon
bulbq <- GET('https://pokeapi.co/api/v2/pokemon/1')
bulbq_parsed <- fromJSON(rawToChar(bulbq$content))
```

```{r}
stat_names <- bulbq_parsed$stats$stat$name
stat_vals <- bulbq_parsed$stats$base_stat

```

```{r}
color_q <- GET('https://pokeapi.co/api/v2/pokemon-color/red')
color_parsed <- fromJSON(rawToChar(color_q$content))
```

```{r}
color_parsed$pokemon_species$name
```
















## Function: pokemon


```{r}
# Building 'Pokemon' Query function
pokemon <- function(pokemon, stats = TRUE){
  
  ###
  # Pulls in height, weight, type and base stats (hp, attack, defense, 
  #  special attack, special defense, speed)
  ###
  
  # Fixing case
  pokemon <- tolower(pokemon)
  
  # Getting API output
  output <- fromJSON(paste0('https://pokeapi.co/api/v2/pokemon/',pokemon,collapse =","))
  
  # Output if user DOES want to see the battle stat attributes of the pokemon
  if(stats == TRUE){
    
  # Loading the data into a vector
  output_row <- c(pokemon,  output$types$type$name[1], output$types$type$name[2],output$height,output$weight,      output$stats$base_stat[1],output$stats$base_stat[2],output$stats$base_stat[3],output$stats$base_stat[4],output$stats$base_stat[5],output$stats$base_stat[6])
  
  # Coercing into a data frame
  output_frame <- as.data.frame(t(output_row))
  colnames(output_frame) <- c("name","type_1","type_2","height","weight","hp","attack","defense","spec_attack","spec_defense","speed")
  
  # Making the numeric variables properly numeric
  output_frame <- transform(output_frame, height = as.numeric(height),weight = as.numeric(weight),hp = as.numeric(hp), attack = as.numeric(attack), defense = as.numeric(defense), spec_attack = as.numeric(spec_attack),spec_defense = as.numeric(spec_defense), speed = as.numeric(speed))
  
  # Returning a nice data frame
  return(output_frame)
  }
  
  # Output if user does NOT want to see the battle stat attributes of the pokemon
  if(stats == FALSE){
    
  # Loading the data into a vector
  output_row <- c(pokemon, output$types$type$name[1], output$types$type$name[2], output$height, output$weight)
  
  # Coercing into a data frame
  output_frame <- as.data.frame(t(output_row))
  colnames(output_frame) <- c("name","type_1","type_2","height","weight")
  
  # Making the numeric variables properly numeric
  output_frame <- transform(output_frame, height = as.numeric(height), weight = as.numeric(weight))
  
  # Returning a nice data frame
  return(output_frame)
  }
}
```


## Function: Pokemon_df

```{r}
# Building a function for pokemon that allows you to pull a df
pokemon_df <- function(all = FALSE, last = NULL){
  
  ###
  # Pulls in height, weight, type and base stats (hp, attack, defense, 
  #  special attack, special defense, speed) for up to a specific pokemon, 
  #  or all pokemon. Note that 'last' can be entered as a number, or as a 
  #  specific pokemon.
  ###
  
  # Fixing case, if last is entered as a specific pokemon
  if(is.character(last) == TRUE){
    last <- tolower(last)
  }
  
  # Accounting for the user entering a specifc pokemon rather than a numeric id
  if(is.numeric(last) == FALSE){
    last_test <- fromJSON(paste0('https://pokeapi.co/api/v2/pokemon/',last,collapse =","))
    last <- last_test$id
  }
  
  # If all = TRUE, returning a df of all pokemon from Generation 1
  # NOTE: This is done to limit the burden on the APi
  if(all == TRUE){
    last <- 151
  }
  
  # Establishing empty df to merge things to
  output_df <- rep("a",11)
  #colnames(output_df) <- c("name","type_1","type_2","height","weight","hp","attack","defense","spec_attack","spec_defense","speed")
  
  for(n in 1:last){
  
    # Getting API output
    output <- fromJSON(paste0('https://pokeapi.co/api/v2/pokemon/',n,collapse =","))
    
    # Loading the data into a vector
    output_row <- c(output$name,  output$types$type$name[1], output$types$type$name[2],output$height,output$weight,         output$stats$base_stat[1],output$stats$base_stat[2],output$stats$base_stat[3],output$stats$base_stat[4],output$stats$base_stat[5],output$stats$base_stat[6])
  
    # Coercing into a data frame
    output_frame <- as.data.frame(t(output_row))
    colnames(output_frame) <- c("name","type_1","type_2","height","weight","hp","attack","defense","spec_attack","spec_defense","speed")
  
    # Making the numeric variables properly numeric
    output_frame <- transform(output_frame, height = as.numeric(height),weight = as.numeric(weight),hp = as.numeric(hp), attack = as.numeric(attack), defense =   as.numeric(defense), spec_attack = as.numeric(spec_attack),spec_defense = as.numeric(spec_defense), speed = as.numeric(speed))
  
  # Adding the stats to the output df
  output_df <- rbind(output_df,output_frame)
  
  }
  
  # Fixing row names and removing extraneous 'starter' row
  output_df <- output_df[-1,]
  rownames(output_df) <- NULL
  
  # Returning our desired data frame
  return(output_df)
  
}
```


```{r}
# Running pokemon_df on all to save for EDA
all_pokemon <- pokemon_df(all = TRUE)

```




















